name: figma_to_flutter
version: 0.1.0
authors:
- Aloïs Deniel <alois.deniel@outlook.com>
description: a tool for generating Flutter widgets from Figma components.
dependencies:
  path_parsing: 0.1.2
  http: 0.11.3+17
  vector_math: 2.0.8
  yaml: 3.1.0
  recase: 4.0.0
  source_gen: 1.1.1
  code_builder: 4.1.0
environment:
  sdk: '>=2.10.0 <3.0.0'