name: figma_to_flutter_cli
description: A cli for converting Figma files to Flutter widgets.
authors:
- Aloïs Deniel <alois.deniel@outlook.com>
environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  args: 1.4.4
  figma_to_flutter:
 
dependency_overrides:
  figma_to_flutter:
    path: ../src